#!/bin/bash

# System Information
HOSTNAME=$(hostname)
OS=$(awk -F= '/PRETTY_NAME/{print $2}' /etc/os-release)
UPTIME=$(uptime -p)

# Hardware Information
PROCESSOR=$(lshw -c cpu | awk '/product/{print $2" "$3}')
CPU_SPEED=$(lshw -c cpu | awk '/capacity/{print $2}')
RAM=$(free -h | awk '/Mem/{print $2}')
DISKS=$(lsblk -o NAME,MODEL,SIZE | sed 's/NAME/Make & Model Size/')
VIDEO_CARD=$(lshw -c display | awk '/product/{print $2" "$3}')

# Network Information
FQDN=$(hostname -f)
IP_ADDRESS=$(ip a | awk '/inet /{print $2}')
GATEWAY=$(ip r | awk '/default via/{print $3}')
DNS_SERVER=$(systemd-resolve --status | awk '/DNS Servers:/{print $3}')

# Interface Information
INTERFACE_NAME=$(ip a | awk '/^[0-9]+:/{print $2}' | head -n 1)
INTERFACE_IP=$(ip a show dev $INTERFACE_NAME | awk '/inet /{print $2}')

# System Status
USERS=$(who | awk '{print $1}' | tr '\n' ',')
DISK_SPACE=$(df -h | awk '/^\/dev/{print $6, $4}')
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGES=$(uptime | awk -F'[a-z]:' '{print $2}')
MEMORY_ALLOC=$(free -h | awk '/Mem/{print $3" used out of "$2}')
LISTENING_PORTS=$(ss -lnt | awk '/LISTEN/{print $4}' | cut -d':' -f2)
UFW_RULES=$(sudo ufw status numbered)

# System Report
cat <<EOF

System Report generated by $USER, $(date "+%Y-%m-%d %H:%M:%S")

System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $PROCESSOR
Speed: $CPU_SPEED
RAM: $RAM
Disk(s): $DISKS
Video: $VIDEO_CARD

Network Information
-------------------
FQDN: $FQDN
Host Address: $IP_ADDRESS
Gateway IP: $GATEWAY
DNS Server: $DNS_SERVER

Interface Information
---------------------
Interface Name: $INTERFACE_NAME
IP Address: $INTERFACE_IP

System Status
-------------
Users Logged In: ${USERS%,}
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Memory Allocation: $MEMORY_ALLOC
Listening Network Ports: ${LISTENING_PORTS%,}
UFW Rules: $UFW_RULES

EOF

